name: Build .NET Project with MSBuild

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for MSBuild

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore HelloWorld.sln  # Replace with your solution file if using NuGet

      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /verbosity:normal

      - name: Execute Additional Command
        run: |
          echo "Executing additional command"
          dir D:\a\DotnetProj1\DotnetProj1\bin\Release
          dir D:\a\DotnetProj1\DotnetProj1\bin

      - name: Zip artifacts
        run: |
          mkdir -p artifacts
          Copy-Item -Path "D:\a\DotnetProj1\DotnetProj1\bin\Release\*" -Destination artifacts\ -Recurse
          Compress-Archive -Path artifacts\ -DestinationPath artifacts.zip
          dir artifacts
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: MyProjectArtifacts
          path: |
            "D:\a\DotnetProj1\DotnetProj1\artifacts.zip"  # Adjust this path to your build output directory
            # Add more paths as needed, each on a new line
