name: Build .NET Project with MSBuild

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: windows-latest  # Use a Windows runner for MSBuild

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore NuGet packages
        run: nuget restore HelloWorld.sln  # Replace with your solution file if using NuGet

      - name: Build with MSBuild
        run: msbuild /p:Configuration=Release /p:Platform="Any CPU" /verbosity:normal
